### ISSUE TITLE
Web page loads fine in browsers, but not in WebPage extension

### ISSUE THREAD

**Issue by mountaindude** [stefanwalther/qvWebPageViewer2#1] opened 2014-02-12 13:15 UTC
I am looking into ways of embedding a Twitter timeline into a QV app.
One option is to take the standard Twitter timeline code created by Twitter when creating a Twitter widget (https://dev.twitter.com/docs/embedded-timelines), placing that code into a very basic web page that is served off IIS on the QV access point.

Having done this, I can access the newly created page (hosted on the QV AP server) from both IE and Chrome (running on the QV publisher server). 
But when entering the same URL into the WebPageViewer2 extension, it does not display correctly.

Not sure if the problem is with the extension or how Iframes work...

The web page is essentially just

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Obama Tweets</title>
</head>
<body>
<a class="twitter-timeline" data-dnt="true" href="https://twitter.com/search?q=%23obama" data-widget-id="<your-widget-id-goes-here>">Tweets about "#obama"</a>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

</body>
</html>

Any ideas?

**Comment by mountaindude** [comment] 2014-02-12 13:17
Duuhh... was not possible to paste HTML into the comments field here... 
Adding some markdown

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Obama Tweets</title>
</head>
<body>
<a class="twitter-timeline" data-dnt="true" href="https://twitter.com/search?q=%23obama" data-widget-id="<your-widget-id-goes-here>">Tweets about "#obama"</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</body>
</html>
```

Any ideas?

**Comment by mountaindude** [comment] 2014-02-12 13:21
Clarification: 

The small web page loads - the text within the anchor <a> tag shows correctly, but no Twitter list is created. iFrame limitation or bug?

**Comment by stefanwalther** [comment] 2014-02-13 22:55
Hi, the better approach would probably the "Minimalistic Html Textbox":
http://www.qlikblog.at/1579/qliktip-39-displaying-html-content-minimalistic-htmltextbox-object-extension/

I'll give it a try and let you know ...

Regards
Stefan

**Comment by mountaindude** [comment] 2014-02-14 13:05
https://dev.twitter.com/docs/embedded-timelines is a good starting point,
it then links to https://twitter.com/settings/widgets which when you are
logged in allows you to create your won widets, which results in a few
lines of code that is to be embedded in a web page of choice.

I will try the other extension, thanks for the suggestion!

/Göran

**Comment by mountaindude** [comment] 2014-02-14 13:11
Hmm, no same problem with the second extension you suggested. Weird. Will
have to push this to next week..

**Comment by stefanwalther** [comment] 2015-03-10 20:25
Cannot reproduce it, close it.

**Closed as completed** 2015-03-10 20:25 UTC
Labels: wontfix
